"""Build the server exclusion mask from the bundled, attributed OSM dataset."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
data = json.loads((root / 'assets/maps/kyzylorda.geojson').read_text(encoding='utf-8'))
features = []
for index, feature in enumerate(data['features']):
    props = feature['properties']
    kind = props.get('kind')
    margin = {'water': 0, 'waterway': 8, 'rail': 20}.get(kind)
    if kind == 'road' and props.get('class') in {'motorway', 'motorway_link', 'trunk', 'trunk_link'}:
        margin = 12
    if margin is not None:
        features.append({'id': f'osm-{index}', 'reason': kind,
                         'margin': margin, 'geometry': feature['geometry']})
encoded = json.dumps(features, separators=(',', ':'), ensure_ascii=True)
sql = """-- Generated by tools/build_territory_restrictions.py from the bundled OSM map.
-- OpenStreetMap contributors, ODbL-1.0; source/license: assets/maps/metadata.json.
-- Water, waterways (8 m), rails (20 m), motorway/trunk roads (12 m).
-- Administrators can add restricted zones; clients have no write privileges.
with source as (select value as f from jsonb_array_elements($osm$
""" + encoded + """
$osm$::jsonb)), projected as (
  select f->>'id' as id,f->>'reason' as reason,(f->>'margin')::double precision as margin,
    extensions.st_transform(extensions.st_makevalid(
      extensions.st_setsrid(extensions.st_geomfromgeojson((f->'geometry')::text),4326)),32641) as geom
  from source
)
insert into public.territory_restrictions(id,reason,geometry)
select id,reason,extensions.st_transform(extensions.st_simplifypreservetopology(
  case when margin>0 then extensions.st_buffer(geom,margin) else geom end,1),4326)
from projected on conflict(id) do update set reason=excluded.reason,geometry=excluded.geometry;
update public.territory_cells c set is_playable=false where exists(
  select 1 from public.territory_restrictions r where extensions.st_intersects(r.geometry,c.geometry));
"""
target = root / 'supabase/migrations/202610070005_territory_restrictions.sql'
target.write_text(sql, encoding='utf-8')
print(f'Wrote {len(features)} exclusions ({target.stat().st_size} bytes).')
